### PR TITLE
Flags support for cli.App

### PR DESCRIPTION
**Pull request by nazhard**

### CODE REVIEW

**Comment by nazhard** [comment]
@multidecay Sorry for the ping, but do you have any ideas for this?

**Comment by multidecay** [comment]
Let me think

**Comment by multidecay** [comment]
Mine found some clue here, https://github.com/multidecay/cli/commit/f332620621e68b7f6ea0f65b5a8e502a62bf78ad#diff-8d9ca23280f24fe6444d03ae46e7a15dd152170f32f57f978dfbdfd3cfe8ff55R89-R93 .

But it still error when it given "-m", if "-m nazan" works. I have idea to patch to manualy inject default value if the next args hasPrefix("-"). But that will annoying if there an array of value without flag value, so I confuse. At least, this for tonight.

**Comment by nazhard** [comment]
I think that's enough. Thank you!

**Pull request merged**
